/** NEWS ACTION TYPES */
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";

export const ADD_NEWS_DETAIL = "ADD_NEWS_DETAIL";
export const ADD_NEWS_DETAIL_SUCCESS = "ADD_NEWS_DETAIL_SUCCESS";
export const ADD_NEWS_DETAIL_FAIL = "ADD_NEWS_DETAIL_FAIL";

export const CLEAR_NEWS = "CLEAR_NEWS";
export const CLEAR_NEWS_SUCCESS = "CLEAR_NEWS_SUCCESS";
export const CLEAR_NEWS_FAIL = "CLEAR_NEWS_FAIL";
  